# Site settings
title: "Vi er Re:"
email: "info@re-cph.com"
description: > # this means to ignore newlines until "baseurl:"
  Meget mere end hjemmesider - Digital samarbejdspartner med fokus på engagement, forståelse og kvalitet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.recopenhagen.com" # the base hostname & protocol for your site
twitter_username: recph
github_username:  re-cph

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']